### ISSUE TITLE
App Crash on scrolling network list

### ISSUE THREAD

**Issue by Satya5614** [uploadcare/uploadcare-android#47]
### Describe the bug

App Crash on scrolling the network list when using uploadcare widget

**Steps to reproduce**

1. Open example app
2. Select "Upload any file from any network" under widget demos
3. Scroll the network list

App crash with **Resources$NotFoundException: Resource ID #0xffffffff**

### Expected behavior

App should not crash and list should scroll

### Code / screenshots

```
2021-12-27 19:16:53.252 10577-10577/com.uploadcare.android.example E/MessageQueue-JNI: android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
        at android.content.res.Resources.getValue(Resources.java:1351)
        at androidx.appcompat.widget.ResourceManagerInternal.createDrawableIfNeeded(ResourceManagerInternal.java:176)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:141)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
        at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
        at androidx.appcompat.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:90)
        at androidx.appcompat.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:98)
        at com.uploadcare.android.widget.utils.BindingAdapters$Companion.setImageBitmap(BindingAdapters.kt:31)
        at com.uploadcare.android.widget.utils.BindingAdapters.setImageBitmap(Unknown Source:2)
        at com.uploadcare.android.widget.databinding.UcwDialogNetworkItemBindingImpl.executeBindings(UcwDialogNetworkItemBindingImpl.java:140)
        at androidx.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:473)
        at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:445)
        at com.uploadcare.android.widget.adapter.SocialNetworksAdapter.getView(SocialNetworksAdapter.kt:54)
        at android.widget.AbsListView.obtainView(AbsListView.java:2405)
        at android.widget.ListView.addViewBelow(ListView.java:3347)
        at android.widget.ListView.scrollListItemsBy(ListView.java:3277)
        at android.widget.ListView.arrowScrollImpl(ListView.java:2760)
        at android.widget.ListView.arrowScroll(ListView.java:2664)
        at android.widget.ListView.commonKey(ListView.java:2425)
        at android.widget.ListView.onKeyDown(ListView.java:2367)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2801)
        at android.view.View.dispatchKeyEvent(View.java:13352)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1917)
        at android.widget.ListView.dispatchKeyEvent(ListView.java:2352)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:453)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1839)
        at android.app.Dialog.dispatchKeyEvent(Dialog.java:825)
        at androidx.appcompat.app.AppCompatDialog.superDispatchKeyEvent(AppCompatDialog.java:208)
        at androidx.appcompat.app.AppCompatDialog$1.superDispatchKeyEvent(AppCompatDialog.java:48)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.appcompat.app.AppCompatDialog.dispatchKeyEvent(AppCompatDialog.java:214)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:367)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5413)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5281)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl
2021-12-27 19:16:53.259 10577-10577/com.uploadcare.android.example D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2021-12-27 19:16:53.264 10577-10577/com.uploadcare.android.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.uploadcare.android.example, PID: 10577
    android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
        at android.content.res.Resources.getValue(Resources.java:1351)
        at androidx.appcompat.widget.ResourceManagerInternal.createDrawableIfNeeded(ResourceManagerInternal.java:176)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:141)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
        at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
        at androidx.appcompat.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:90)
        at androidx.appcompat.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:98)
        at com.uploadcare.android.widget.utils.BindingAdapters$Companion.setImageBitmap(BindingAdapters.kt:31)
        at com.uploadcare.android.widget.utils.BindingAdapters.setImageBitmap(Unknown Source:2)
        at com.uploadcare.android.widget.databinding.UcwDialogNetworkItemBindingImpl.executeBindings(UcwDialogNetworkItemBindingImpl.java:140)
        at androidx.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:473)
        at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:445)
        at com.uploadcare.android.widget.adapter.SocialNetworksAdapter.getView(SocialNetworksAdapter.kt:54)
        at android.widget.AbsListView.obtainView(AbsListView.java:2405)
        at android.widget.ListView.addViewBelow(ListView.java:3347)
        at android.widget.ListView.scrollListItemsBy(ListView.java:3277)
        at android.widget.ListView.arrowScrollImpl(ListView.java:2760)
        at android.widget.ListView.arrowScroll(ListView.java:2664)
        at android.widget.ListView.commonKey(ListView.java:2425)
        at android.widget.ListView.onKeyDown(ListView.java:2367)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2801)
        at android.view.View.dispatchKeyEvent(View.java:13352)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1917)
        at android.widget.ListView.dispatchKeyEvent(ListView.java:2352)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:453)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1839)
        at android.app.Dialog.dispatchKeyEvent(Dialog.java:825)
        at androidx.appcompat.app.AppCompatDialog.superDispatchKeyEvent(AppCompatDialog.java:208)
        at androidx.appcompat.app.AppCompatDialog$1.superDispatchKeyEvent(AppCompatDialog.java:48)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.appcompat.app.AppCompatDialog.dispatchKeyEvent(AppCompatDialog.java:214)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:367)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5413)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5281)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
2021-12-27 19:16:53.268 10577-10577/com.uploadcare.android.example E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7505)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7474)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7435)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7630)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    
    
    --------- beginning of system

````

### Environment

 - Library version: 3.1.0
 - Language/framework version:
 - OS version:  Android

**Comment by rsedykh** [comment]
Hi. Sorry for the extremely late response. This issue should be long gone (since 3.1.0). We've just released https://github.com/uploadcare/uploadcare-android/releases/tag/4.0.0 and we couldn't reproduce this issue.
