### ISSUE TITLE
onFailure invoked although file uploaded

### ISSUE THREAD

**Issue by kitchgram** [uploadcare/uploadcare-android#53]
### Describe the bug

Storing an mp4 uploads the file successfully (I can see it in the dashboard) but getting onFailure where message is a string containing code=400

### Code / screenshots

`com.uploadcare.android.library.exceptions.UploadFailureException: Response{protocol=h2, code=400, message=, url=https://api.uploadcare.com/files/79f25963-74b0-473a-bec4-052cbc816066/}
                                                                                                    	at com.uploadcare.android.library.upload.FileUploader$uploadAsync$1$2.invokeSuspend(FileUploader.kt:258)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

### Environment

 - Library version: 3.1.0
 - Language/framework version:
 - OS version: Emulator latest android version

**Comment by rsedykh** [comment]
Hi. Sadly we can't fix it right now due to the current lack of android dev on board. :-( If you have a solution, we would love to receive a PR.

**Comment by rsedykh** [comment]
We've tried to reproduce it, but failed. :-( Can you still reproduce it with the latest release?
